import AppShell from "@/components/AppShell";
import Center from "@/components/Center";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Multiple",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Center>
          <AppShell>{children}</AppShell>
        </Center>
      </body>
    </html>
  );
}
